config/routes.rb
Rails.application.routes.draw do
  resources :people
  root 'people#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  def self.sortString(sort)
    if !sort.present? || !sort.include?("-") then
      return nil
    elsif sort == "address-desc" then
      return "street DESC, city DESC, zip DESC, country DESC"
    elsif sort.include? "address" then
      return "street, city, zip, country"
    end

    sort_prefs = sort.split("-")
    if (sort_prefs.length() != 2) then
      return nil
    end

    order = sort_prefs[0]
    if sort_prefs[1] == 'desc' then
      order = order + " DESC"
    end
    order
  end

  def self.filter(name: nil, email: nil, phone: nil, address: nil)
    name = name ? "%#{name.downcase}%" : "%"
    email = email ? "%#{email.downcase}%" : "%"
    phone = phone ? "%#{phone.downcase}%" : "%"
    address = address ? "%#{address.downcase}%" : "%"

    Person.where("lower(name) LIKE ?", name)
      .where("lower(email) LIKE ?", email)
      .where("lower(phone) LIKE ?", phone)
      .where("lower(street) LIKE ? OR lower(city) LIKE ? OR lower(zip) LIKE ? OR lower(country) LIKE ?",
        address, address, address, address)
  end

  def address
    street + "\n" + city + ", " + zip + "\n" + country
  end

  def address_includes?(str)
    str = str ? str.downcase : ""
    street = self.street ? self.street.downcase : ""
    city = self.city ? self.city.downcase : ""
    zip = self.zip ? self.zip.downcase : ""
    country = self.country ? self.country.downcase : ""

    street.include?(str) || city.include?(str) || zip.include?(str) || country.include?(str)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @filter = filter_params
    @sort = params[:sort]
    @people = Person.filter(name: @filter[:name],
        email: @filter[:email],
        phone: @filter[:phone],
        address: @filter[:address])
      .order(Person.sortString(@sort))
  end

  private
    def filter_params
      params.permit(:name, :phone, :email, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TabelleRailsExample</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://unpkg.com/tabelle@1.0.0-2/dist/tabelle.css" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <script src="https://unpkg.com/tabelle@1.0.0-2/dist/tabelle.js"></script>
  </body>
</html>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<ta-belle id="tabelle" search-src="/" sort="<%= @sort %>" change-uri debounce="600">
  <table>
    <thead>
      <tr>
        <th name="name" value="<%= @filter[:name] %>">Name</th>
        <th name="phone" value="<%= @filter[:phone] %>">Phone</th>
        <th name="email" value="<%= @filter[:email] %>">Email</th>
        <th name="address" value="<%= @filter[:address] %>">Address</th>
      </tr>
    </thead>

    <tbody>
      <% @people.each do |person| %>
        <tr>
          <td><%= person.name %></td>
          <td><%= person.phone %></td>
          <td><%= person.email %></td>
          <td>
            <div><%= person.street %></div>
            <div><%= person.city %>, <%= person.zip %></div>
            <div><%= person.country %></div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</ta-belle>

<br>

<%# link_to 'New Person', new_person_path %>